### ISSUE TITLE
Bump to latest and greated

### ISSUE THREAD

**Issue by orefalo** [jednano/ts-compiler#3]
Can I suggest a compiler bump to the latest and greatest

tsc --version  
message TS6029: Version 1.1.0.1

Thank you

**Comment by jednano** [comment]
There's no typescript-api for v1.1.0.1, but can I ask how you're using this module? If you're using gulp, might I suggest [gulp-typescript](https://github.com/ivogabe/gulp-typescript)?

**Comment by orefalo** [comment]
I am doing an integration with meteor

https://github.com/meteor-typescript/meteor-typescript-compiler https://github.com/meteor-typescript/meteor-typescript-compiler

It works!

**Comment by jednano** [comment]
It looks like we have to wait until [TypeScript 1.3](https://github.com/Microsoft/TypeScript/wiki/Roadmap#13) before we have an official TypeScript API.

Well, I'd be willing to accept any pull requests on both the typescript-api repos as well as this one, but it's going to be a lot more work than I can commit to right now, as I have no way to automate the process. Currently, It's a tedious copy and paste to create the [typescript-api.d.ts file](https://github.com/jedmao/typescript-api/blob/master/typescript-api.d.ts).

**Comment by orefalo** [comment]
Hi Jed,

I know, no official API for TS.  That’s why I use your pkg.
  What’s wrong with yet another copy/paste of the latest TS version ?

Oli

**Comment by jednano** [comment]
It just takes a while. It's a tedious process, because you have to rename some things and such. Again, totally willing to accept PRs for both repos.

**Comment by orefalo** [comment]
Jed you realize i don't have the expertise...

**Comment by jednano** [comment]
Look, I took a stab at it just now and, honestly, I'm surprised I got it to work the first time around. And since then? They've totally changed the compiler, so it's not an easy task. The BatchCompiler, which this module used, is totally removed or renamed to something else. I don't even know what I'm looking at any more and it will take too much of my time to figure it all out.

I strongly suggest you utilize the [gulp-typescript](https://github.com/ivogabe/gulp-typescript) module for what you're trying to do. You don't have to use gulp to utilize the tool, plus the author has been very responsive of recent, so I'm sure if there are any issue with the plugin they will shortly be resolved. For your purposes, you might need to use [vinyl-fs](https://github.com/wearefractal/vinyl-fs) to pipe your files through gulp-typescript and get exactly what you need. You can see me doing essentially the same thing in my [blink project tests](https://github.com/jedmao/blink/blob/0391a5db15ae1f274df7bfccc397b60f66479d3b/test/spec/lib/bundle.spec.ts#L17-L25).

Here's [an example of me using gulp-typescript](https://github.com/jedmao/blink/blob/0391a5db15ae1f274df7bfccc397b60f66479d3b/tasks/scripts.js#L8-L24) as well.

Good luck!

**Comment by orefalo** [comment]
I’ll take that suggestion.

I went from a project call typescript-api to ts-compiler, and now to gulp-ts
   It’s about time they standardize.

Thanks for the pointers.

Sincerely,

**Comment by jednano** [comment]
I suppose standardization comes with TypeScript 1.3, when they expose an API. Not entirely sure, but everything you're using is unofficial, so don't expect too much.
