### ISSUE TITLE
TypeScript 1.5

### ISSUE THREAD

**Issue by simonexmachina** [jednano/ts-compiler#4]
Any plans to support TypeScript 1.5?

**Comment by jednano** [comment]
No. I suggest using [gulp-typescript](https://www.npmjs.com/package/gulp-typescript).

**Comment by simonexmachina** [comment]
Cool, thanks. I'm working on TypeScript 1.5 support in a broccoli plugin, so I'll probably be working on broccoli-typescript, which uses ts-compiler. I'll investigate doing a PR to this repository, or I can use gulp-typescript as a guide. Any thoughts you want to offer on updating this project to support 1.5?

**Comment by jednano** [comment]
They've totally changed the internals of the TypeScript API since [typescript-api](https://github.com/jedmao/typescript-api) was created. Besides, you can just `require('typescript')` [since version 1.4](https://github.com/jedmao/typescript-api/issues/1#issuecomment-76141658), so if this lib were to be updated it should stop using typescript-api as a dependency and use the typescript module directly.

Since the internals have changed so much though, it would be like starting this project over. You're free to start your own GitHub repo that does this or you can modify this project and I'll accept the PR.

**Comment by jednano** [comment]
@aexmachina I've just given you push access to this repo.

**Comment by jednano** [comment]
@aexmachina I can add you to the npm users as well (when needed).

**Comment by simonexmachina** [comment]
Okay, cool. Thanks! Not sure which way I'll go right now, but thanks for the info.
